openapi: 3.2.0
info:
  title: PeerTube Instance Follows API
  version: 8.1.0
  contact:
    name: PeerTube Community
    url: https://joinpeertube.org
  license:
    name: AGPLv3.0
    url: https://github.com/Chocobozzz/PeerTube/blob/master/LICENSE
  x-logo:
    url: https://joinpeertube.org/img/brand.png
    altText: PeerTube Project Homepage
  description: The PeerTube API is built on HTTP(S) and is RESTful.
servers:
- url: https://peertube2.cpy.re
  description: Live Test Server (live data - latest nightly version)
- url: https://peertube3.cpy.re
  description: Live Test Server (live data - latest RC version)
- url: https://peertube.cpy.re
  description: Live Test Server (live data - stable version)
tags:
- name: Instance Follows
  description: Managing servers which the instance interacts with is crucial to the concept of federation in PeerTube and external video indexation. The PeerTube server then deals with inter-server ActivityPub operations and propagates information across its social graph by posting activities to actors' inbox endpoints.
  externalDocs:
    url: https://docs.joinpeertube.org/admin/following-instances#instances-follows
paths:
  /api/v1/server/followers:
    get:
      tags:
      - Instance Follows
      summary: List instances following the server
      parameters:
      - $ref: '#/components/parameters/followState'
      - $ref: '#/components/parameters/actorType'
      - $ref: '#/components/parameters/start'
      - $ref: '#/components/parameters/count'
      - $ref: '#/components/parameters/sort'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                    example: 1
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Follow'
      operationId: getApiV1ServerFollowers
      x-operation-id-source: derived
  /api/v1/server/followers/{handle}:
    delete:
      summary: Remove or reject a follower to your server
      security:
      - OAuth2:
        - admin
      tags:
      - Instance Follows
      parameters:
      - name: handle
        in: path
        required: true
        description: The remote actor handle to remove from your followers
        schema:
          type: string
          format: email
      responses:
        '204':
          description: successful operation
        '404':
          description: follower not found
      operationId: deleteApiV1ServerFollowersByHandle
      x-operation-id-source: derived
  /api/v1/server/followers/{handle}/reject:
    post:
      summary: Reject a pending follower to your server
      security:
      - OAuth2:
        - admin
      tags:
      - Instance Follows
      parameters:
      - name: handle
        in: path
        required: true
        description: The remote actor handle to remove from your followers
        schema:
          type: string
          format: email
      responses:
        '204':
          description: successful operation
        '404':
          description: follower not found
      operationId: postApiV1ServerFollowersByHandleReject
      x-operation-id-source: derived
  /api/v1/server/followers/{handle}/accept:
    post:
      summary: Accept a pending follower to your server
      security:
      - OAuth2:
        - admin
      tags:
      - Instance Follows
      parameters:
      - name: handle
        in: path
        required: true
        description: The remote actor handle to remove from your followers
        schema:
          type: string
          format: email
      responses:
        '204':
          description: successful operation
        '404':
          description: follower not found
      operationId: postApiV1ServerFollowersByHandleAccept
      x-operation-id-source: derived
  /api/v1/server/following:
    get:
      tags:
      - Instance Follows
      summary: List instances followed by the server
      parameters:
      - $ref: '#/components/parameters/followState'
      - $ref: '#/components/parameters/actorType'
      - $ref: '#/components/parameters/start'
      - $ref: '#/components/parameters/count'
      - $ref: '#/components/parameters/sort'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                    example: 1
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Follow'
      operationId: getApiV1ServerFollowing
      x-operation-id-source: derived
    post:
      security:
      - OAuth2:
        - admin
      tags:
      - Instance Follows
      summary: Follow a list of actors (PeerTube instance, channel or account)
      responses:
        '204':
          description: successful operation
        '500':
          description: cannot follow a non-HTTPS server
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                hosts:
                  type: array
                  items:
                    type: string
                    format: hostname
                  uniqueItems: true
                handles:
                  type: array
                  items:
                    type: string
                  uniqueItems: true
      operationId: postApiV1ServerFollowing
      x-operation-id-source: derived
  /api/v1/server/following/{hostOrHandle}:
    delete:
      summary: Unfollow an actor (PeerTube instance, channel or account)
      security:
      - OAuth2:
        - admin
      tags:
      - Instance Follows
      parameters:
      - name: hostOrHandle
        in: path
        required: true
        description: The hostOrHandle to unfollow
        schema:
          type: string
      responses:
        '204':
          description: successful operation
        '404':
          description: host or handle not found
      operationId: deleteApiV1ServerFollowingByHostOrHandle
      x-operation-id-source: derived
components:
  parameters:
    followState:
      name: state
      in: query
      schema:
        type: string
        enum:
        - pending
        - accepted
    start:
      name: start
      in: query
      required: false
      description: Offset used to paginate results
      schema:
        type: integer
        minimum: 0
    sort:
      name: sort
      in: query
      required: false
      description: Sort column
      schema:
        type: string
        example: -createdAt
    actorType:
      name: actorType
      in: query
      schema:
        type: string
        enum:
        - Person
        - Application
        - Group
        - Service
        - Organization
    count:
      name: count
      in: query
      required: false
      description: Number of items to return
      schema:
        type: integer
        default: 15
        maximum: 100
        minimum: 1
  schemas:
    Actor:
      properties:
        id:
          $ref: '#/components/schemas/id'
        url:
          type: string
          format: url
        name:
          description: immutable name of the actor, used to find or mention it
          allOf:
          - $ref: '#/components/schemas/username'
        avatars:
          type: array
          items:
            $ref: '#/components/schemas/ActorImage'
        host:
          type: string
          format: hostname
          description: server on which the actor is resident
        hostRedundancyAllowed:
          type:
          - boolean
          - 'null'
          description: whether this actor's host allows redundancy of its videos
        followingCount:
          type: integer
          minimum: 0
          description: number of actors subscribed to by this actor, as seen by this instance
        followersCount:
          type: integer
          minimum: 0
          description: number of followers of this actor, as seen by this instance
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Follow:
      properties:
        id:
          $ref: '#/components/schemas/id'
        follower:
          $ref: '#/components/schemas/Actor'
        following:
          $ref: '#/components/schemas/Actor'
        score:
          type: number
          description: score reflecting the reachability of the actor, with steps of `10` and a base score of `1000`.
        state:
          type: string
          enum:
          - pending
          - accepted
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    ActorImage:
      properties:
        path:
          description: Deprecated in PeerTube v8.0, use fileUrl instead
          deprecated: true
          type: string
        fileUrl:
          description: '**PeerTube >= 7.1**'
          type: string
        width:
          type: integer
        height:
          type: integer
          description: '**PeerTube >= 7.3**'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    username:
      type: string
      description: immutable name of the user, used to find or mention its actor
      example: chocobozzz
      pattern: /^[a-z0-9._]+$/
      minLength: 1
      maxLength: 50
    id:
      type: integer
      minimum: 1
      example: 42
  securitySchemes:
    OAuth2:
      description: 'Authenticating via OAuth requires the following steps:

        - Have an activated account

        - [Generate] an access token for that account at `/api/v1/users/token`.

        - Make requests with the *Authorization: Bearer <token\>* header

        - Profit, depending on the role assigned to the account


        Note that the __access token is valid for 1 day__ and is given

        along with a __refresh token valid for 2 weeks__.


        [Generate]: https://docs.joinpeertube.org/api/rest-getting-started

        '
      type: oauth2
      flows:
        password:
          tokenUrl: /api/v1/users/token
          scopes:
            admin: Admin scope
            moderator: Moderator scope
            user: User scope
externalDocs:
  url: https://docs.joinpeertube.org/api-rest-reference.html
x-tagGroups:
- name: Static endpoints
  tags:
  - Static Video Files
- name: Download
  tags:
  - Video Download
- name: Feeds
  tags:
  - Video Feeds
- name: Auth
  tags:
  - Register
  - Session
- name: Accounts
  tags:
  - Accounts
  - Users
  - User Exports
  - User Imports
  - My User
  - My Subscriptions
  - My Notifications
  - My History
- name: Videos
  tags:
  - Video
  - Video Upload
  - Video Imports
  - Video Captions
  - Video Chapters
  - Video Channels
  - Video Comments
  - Video Rates
  - Video Playlists
  - Video Stats
  - Ownership Change
  - Video Mirroring
  - Video Files
  - Video Transcoding
  - Live Videos
  - Channels Sync
  - Video Passwords
  - Video Embed Privacy
- name: Search
  tags:
  - Search
- name: Moderation
  tags:
  - Abuses
  - Video Blocks
  - Account Blocklist
  - Server Blocklist
  - Automatic Tags
  - Watched Words
- name: Instance
  tags:
  - Config
  - Client Config
  - Homepage
  - Instance Follows
  - Instance Redundancy
  - Plugins
  - Stats
  - Logs
  - Job
- name: Remote Jobs
  tags:
  - Runner Registration Token
  - Runner Jobs
  - Runners
